phase1/Models/product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phase1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual category category { get; set; }
    }
}

phase1/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace phase1.Controllers
{
    public class CartsController : Controller
    {
        // GET: Carts
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddToCart(int id)
        {
            var cart = new cart();
            DateTime localDate = DateTime.Now;
            cart.added_at = localDate;
            cart.product_Id = id;
            var cart2 = db.carts.Find(id);
            if (cart2 != null)
            {
                return RedirectToAction("Filter", "products");
            }
            else
            {
                db.carts.Add(cart1);
                db.SaveChanges();
                return RedirectToAction("Filter", "products");
            }
        }
        public ActionResult Remove(int id)
        {
            var _cart = db.carts.Find(id);
            if (_cart != null)
            {
                db.carts.Remove(_cart);
            }
            db.SaveChanges();
            return RedirectToAction("Filter", "products");
        }

    }
}

phase1/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using phase1.Models;
using System.IO;


namespace phase1.Controllers
{
    public class productsController : Controller
    {
        private storeEntities db = new storeEntities();

        // GET: products
        public ActionResult Index()
        {
            var products = db.products.Include(p => p.category);
            return View(products.ToList());
        }

        // GET: products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: products/Create
        public ActionResult Create()
        {
            ViewBag.category_id = new SelectList(db.categories, "Id", "name");
            return View();
        }

        // POST: products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,name,price,image,description,category_id")] product product)
        {
            if (ModelState.IsValid)
            {
                db.products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.category_id = new SelectList(db.categories, "Id", "name", product.category_id);
            return View(product);
        }

        // GET: products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.category_id = new SelectList(db.categories, "Id", "name", product.category_id);
            return View(product);
        }

        // POST: products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,name,price,image,description,category_id")] product product,HttpPostedFileBase imgfile)
        {
            if (ModelState.IsValid)
            {
                string loc = "";
                if (imgfile.FileName.Length > 0) {
                    loc = "~/images/" + Path.GetFileName(imgfile.FileName);
                    imgfile.SaveAs(Server.MapPath(loc));
                }
                product.image = loc;
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.category_id = new SelectList(db.categories, "Id", "name", product.category_id);
            return View(product);
        }

        // GET: products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            product product = db.products.Find(id);
            db.products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




        public ActionResult homepage()
        {
            var record = db.products.ToList();
            return View(record);
        }


        public ActionResult Filter(string search)
        {
            var products = db.products.Include(p => p.category).ToList();

            if (!String.IsNullOrEmpty(search))
            {
                products = products.Where(item => item.category.name.Contains(search) || search == null).ToList();
            }
            var cart = db.carts.ToList();
            var Viewmodel = new ProductCarts
            {
                carts = cart,
                products = products
            };
            return View(Viewmodel);
        }
    }
}

phase1/Views/products/Create.cshtml
@model phase1.Models.product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/productlayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>pro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

phase1/Views/products/Delete.cshtml
@model phase1.Models.product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/productlayout.cshtml";

}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category.name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

phase1/Views/products/Details.cshtml
@model phase1.Models.product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/productlayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>product</h4>
    <hr />



    <p>@Html.DisplayFor(model => model.name)&nbsp;@Html.DisplayFor(model => model.price)&nbsp;EGP</p>
    @*<img src="@Url.Content(@model.image)" width=50 />*@

    <img src="@Url.Content(Model.image)" width="300" height="350" />


    <p>@Html.DisplayFor(model => model.description)</p>

    @*<img src="@Html.DisplayFor(model => model.image)" width=50/>*@


    <p>

        <a href="@Url.Action("Edit","products",new {id =  @Html.DisplayFor(model => model.Id) })" class="btn btn-primary" target="_blank"><span class="glyphicon glyphicon-plus"></span> Update</a>
        <a href="@Url.Action("Delete","products",new {id =  @Html.DisplayFor(model => model.Id) })" class="btn btn-primary" target="_blank"><span class="glyphicon glyphicon-minus"></span> Delete</a>


        @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")*@
    </p>

phase1/Views/products/Edit.cshtml
@model phase1.Models.product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/productlayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit","products",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <input type="file" value="imgfile" name="imgfile" />
                @*@Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category_id, "category_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("category_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.category_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

phase1/Views/products/Filter.cshtml
@model phase1.Viewmodel.ProductCarts


@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    <div class="container" style="width:100%;margin-top:2%">
        <a href="href=" @Url.Action("Index", "carts", null) class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal" role="button">Show my cart</a>
        <div class="modal fade" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">

                    <div class="modal-header">
                        <a href="#" class="close" data-dismiss="modal">&times;</a>
                        <h3 class="modal-title">Cart</h3>
                    </div>
                    <div class="modal-body">
                        <form id="myForm">
                            <table class="table">
                                @foreach (var item in Model.carts)
                                {
                                    <tr>
                                        <td>
                                            <a href=" @Url.Action("Remove","Carts",new { id=item.product_Id } )" class="btn btn-primary">Remove</a>
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.product.Name) - @Html.DisplayFor(modelItem => item.product.Price) EGP<br />
                                            @Html.DisplayFor(modelItem => item.added_at)
                                        </td>
                                    </tr>
                                }

                            </table>
                        </form>
                        <div style="text-align:center;display:none" id="loaderDiv">
                            <img src="~/Content/InternetSlowdown_Day.gif" width="150" /> @* //put any image in content folder*@
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a href="@Url.Action("Filter", "Products", null)" class="btn btn-default" data-dismiss="modal">Cancel</a>
                        @*<input type="reset" value="Submit" class="btn btn-success" id="btnSubmit" />*@
                    </div>
                </div>
            </div>
        </div>
    </div>
}
<h2>Products</h2>
@using (Html.BeginForm())

{
    <br />
    <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon">@@</span>
                @Html.TextBox("search", null, new { Type = "text", @class = "form-control" })
                <span class="input-group-btn">
                    @Html.ActionLink("Add New Product", "Create", null, new { @class = "btn btn-primary" })
                </span>
            </div>
        </div>
    </form>
    <br />
}

<table class="table">

    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details","products")">
                    <img src="@Url.Content(item.image)" alt="..." width="242" height="200">
                </a>
                <div class="caption">
                    <a href="@Url.Action("Details","products",new {id=@item.Id })" class="btn btn-primary" role="button" target="_blank">Details</a>
                    <h3>@item.price</h3>
                    <h3>@item.name</h3>
                </div>
            </div>
        </div>
    }
</table>
<script>
    $(document).ready(function () {
        $("#btnSubmit").click(function () {
            $("#loaderDiv").show();
            var myformdata = $("#myForm").serialize();
            $.ajax({
                type: "POST",
                url: "/Test/Index",
                data: myformdata,
                success: function () {
                    $("#loaderDiv").hide();
                    $("#myModal").modal("hide");
                }
            })
        })
    })
</script>

phase1/Views/products/Index.cshtml
@model IEnumerable<phase1.Models.product>


    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/productlayout.cshtml";
    }

        <h2>Index</h2>

        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.image)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.category.name)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.price)
                    </td>

                    <td>

                        <img src="@Url.Content(item.image)" width=40 />
                        @*@Html.DisplayFor(modelItem => item.image)*@
                    </td>
                    
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.category.name)
                    </td>
                    
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>

phase1/Views/products/homepage.cshtml
@model IEnumerable<phase1.Models.product>

@{
    ViewBag.Title = "homepage";
    Layout = "~/Views/Shared/productlayout.cshtml";
}

<h2>homepage</h2>

<p style="position:absolute;right:105px;">
    <a href="@Url.Action("Create","products")" class="btn btn-primary" target="_blank"><span class="glyphicon glyphicon-plus"></span> Add Product</a>
</p>
<br />
<br />

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="@Url.Content(item.image)" alt="...">
                <div class="caption">
                    <h3>@Url.Content(item.name)</h3>
                    <p>@Url.Content(item.price)</p>
                    <p><a href="@Url.Action("Details","products",new {id=@item.Id })" class="btn btn-primary" role="button" target="_blank">Details</a> </p>
                </div>
            </div>
        </div>

    }

</div>